package com.mycompany.app;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;

import java.time.Duration;
import java.util.concurrent.TimeUnit;

import java.util.*;
public class SearchColleagueTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchColleague() {

    driver.get("https://login.starmeup.com/?continue=aHR0cHM6Ly9hcHAuc3Rhcm1ldXAuY29tL2hvbWU%3D&logout=true&origin=SMU_WEB_v3");
    driver.manage().window().setSize(new Dimension(1792, 1010));
    driver.findElement(By.name("identification-text")).sendKeys("christian.vera@globant.com");
    driver.findElement(By.cssSelector(".button")).click();;
    {
      WebElement element = waitForElement(By.cssSelector(".button"), 10);

      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = waitForElement(By.tagName("body"), 10);
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = waitForElement(By.cssSelector(".button--fluid"), 10);
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    WebElement click = waitForElement(By.cssSelector(".button--fluid"), 10);
    
    if (click != null) {
      



    try {
      
      click.click();
      waitForStaleness(click, 10);
      
      // Wait for the fluid button to become stale after clicking
    
    //   try {
    //     waitForStaleness(click, 10); // Wait until the button is removed from the DOM
    //     System.out.println("The button has been removed from the DOM.");
    // } catch (TimeoutException e) {
    //     System.out.println("The button did not become stale. It might still be present.");
    // }

    } catch (StaleElementReferenceException e) {

      System.out.println("The button did not become stale. It might still be present.");
      // T
    }
       
  }

    // {
    //   WebElement element = waitForElement(By.linkText("Christian Santiago Vera Rojas"),10);
    //   Actions builder = new Actions(driver);
    //   builder.moveToElement(element).perform();
    // }
    // {
    //   WebElement element = waitForElement(By.tagName("body"), 10);
    //   Actions builder = new Actions(driver);
    //   builder.moveToElement(element, 0, 0).perform();
    // }

    

    
    // driver.get("https://login.starmeup.com/");
    // driver.manage().window().setSize(new Dimension(850, 966));
    // driver.findElement(By.name("identification-text")).click();
    // driver.findElement(By.name("identification-text")).sendKeys("christian.vera@globant.com");
    // driver.findElement(By.cssSelector(".button")).click();
    // driver.findElement(By.cssSelector(".button--fluid")).click();
    // {
    //     WebElement element = waitForElement(By.cssSelector(".swiper-slide-next > .mx-auto"), 10);
    //      Actions builder = new Actions(driver);
    //      builder.moveToElement(element).perform();
    // }
    // driver.findElement(By.cssSelector(".main-search__input")).click();
    // driver.findElement(By.cssSelector(".main-search__input")).sendKeys("carlos sandoval");
    // driver.findElement(By.cssSelector(".main-search-list-item:nth-child(2) .main-search-list-item__name")).click();
    //      {
    //      WebElement element = waitForElement(By.cssSelector(".ui-user-profile-user-actions__more"), 10);
    //      Actions builder = new Actions(driver);
    //      builder.moveToElement(element).perform();
    // }
     //driver.findElement(By.cssSelector(".profile-metric__link:nth-child(2) .metric-icon")).click();
  }

  private WebElement waitForElement(By by, int timeoutInSeconds) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(timeoutInSeconds));
        try {
            return wait.until(ExpectedConditions.visibilityOfElementLocated(by)); // Wait until the element is visible
        } catch (StaleElementReferenceException e) {
            // Handle stale element by returning null
            return null;
        }
    }

    private void waitForStaleness(WebElement element, int timeoutInSeconds) {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(timeoutInSeconds));
      wait.until(ExpectedConditions.stalenessOf(element)); // Wait until the element is no longer attached to the DOM
  }
}
